Update helm-test.yml

diff --git a/.github/workflows/helm-test.yml b/.github/workflows/helm-test.yml
--- a/.github/workflows/helm-test.yml
+++ b/.github/workflows/helm-test.yml
@@ -8,7 +8,7 @@ on:
       - 'helm/**'
 
 jobs:
-  lint-test:
+  test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -38,12 +38,8 @@ jobs:
           fi
 
       - name: Run chart-testing (lint)
-#        if: steps.list-changed.outputs.changed == 'true'
+        if: steps.list-changed.outputs.changed == 'true'
         run: ct lint --target-branch ${{ github.event.repository.default_branch }}
-
-#       - name: Create kind cluster
-# #        if: steps.list-changed.outputs.changed == 'true'
-#         uses: helm/kind-action@v1.4.0
         
       # Run micro Kubernetes cluster for testing purposes
       - uses: AbsaOSS/k3d-action@v2
@@ -55,10 +51,11 @@ jobs:
             --k3s-arg "--no-deploy=traefik,servicelb,metrics-server@server:*"
 
       - name: Run chart-testing (install)
-#        if: steps.list-changed.outputs.changed == 'true'
+        if: steps.list-changed.outputs.changed == 'true'
         run: ct install --target-branch ${{ github.event.repository.default_branch }}
 
       - name: Login to Docker Hub
+#        if: steps.list-changed.outputs.changed == 'true'
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -79,15 +76,24 @@ jobs:
           kubectl logs -l app=golden-devops-helm-release --namespace=prod-namespace
           echo "------------------------------------------------------------------------"
 
-      - name: Test Helm resources (curl)
+      - name: Test Helm resources (curl command)
 #        if: steps.list-changed.outputs.changed == 'true'
         run: |
-          kubectl exec deploy/golden-devops-helm-release --namespace=prod-namespace -- curl --fail localhost || echo "Successfully retrieved data from localhost!"
+          if ! kubectl exec deploy/golden-devops-helm-release --namespace=prod-namespace -- curl --fail localhost; then
+            echo "Failed to retrieve data from localhost!"
+            exit 1
+          fi
 
-      - name: Test Helm resources (wget)
+      - name: Test Helm resources (wget with testing container)
 #        if: steps.list-changed.outputs.changed == 'true'
         run: |
-          helm test golden-devops-helm-release || echo "Testing of Helm golden-devops-helm-release failed!"
+          if ! helm test golden-devops-helm-release; then
+            echo "Testing of Helm golden-devops-helm-release failed!"
+            echo "---------------------------Testing container logs--------------------------"
+            kubectl logs golden-devops-helm-release-connection-test --namespace=prod-namespace
+            echo "---------------------------------------------------------------------------"
+            exit 1
+          fi
           echo "---------------------------Testing container logs--------------------------"
           kubectl logs golden-devops-helm-release-connection-test --namespace=prod-namespace
           echo "---------------------------------------------------------------------------"
